### PR TITLE
Set Stripe bitcoin option to true

### PR DESCRIPTION
**Pull request by anrddh**
#210

### CODE REVIEW

**Comment by ppannuto** [comment]
This is a good first part, but Stripe charges a different fee for credit card and bitcoin transactions. So the math needs to change depending on how the user pays for how much actually credit their account.

**Comment by awesomeaniruddh** [comment]
The new charge for Bitcoin is stored in the variable `bitcoin_charge`, but I'm not sure how to make Stripe charge that amount for Bitcoin.

Acc to these docs (https://stripe.com/docs/bitcoin#using-stripejs), this is possible using a JavaScript library. Not sure if it's already being used elsewhere, or you'd like me to integrate it (I'd probably need some help if that, I'm not familiar with Django).

**Comment by ppannuto** [comment]
We currently just use Stripe checkout (https://stripe.com/docs/checkout)
which is a simpler thing stripe built on top of stripe.js - I believe
stripe has documentation on how to go from one to the other.

Betty is built on Pyramid ( https://trypyramid.com/ ) not Django, though I
suspect the core ideas are similar.

I don't think any of the core betty folk have a ton of time to help out
with software dev right now I'm afraid, but happy to keep giving pointers
for you to move forward

**Comment by awesomeaniruddh** [comment]
Moving from Stripe Checkout to Stripe.js will require building our own form. I'm looking for a workaround.

**Comment by awesomeaniruddh** [comment]
The easiest solution is to just make another button just for bitcoin.

**Comment by ppannuto** [comment]
That seems like a fine solution.

Don't lose track of everything that'll need to change after the button too. It'll need to post to a different end point (i.e. not https://github.com/um-cseg/chez-betty/blob/44e052ca29f7c305549e76588b5d931150558d17/chezbetty/views_user.py#L196 ) and you'll need to make a variant of this https://github.com/um-cseg/chez-betty/blob/44e052ca29f7c305549e76588b5d931150558d17/chezbetty/utility.py#L326 that correctly validates the bitcoin fee, then a new transaction type https://github.com/um-cseg/chez-betty/blob/master/chezbetty/models/transaction.py#L666 -- I don't think the legacy BTCDeposit will work, probably too tied to the Coinbase API.

Once all that's in place, the next step is making sure all the analytics and cash reporting dashboards understand the new money pool.

**Pull request closed without merging**
