### PR TITLE
Disambiguate names under certain circumstances

### PR DESCRIPTION
**Pull request by arxanas**
pls

### CODE REVIEW

**Comment by ppannuto** [comment]
This will only affect https://chezbetty.eecs.umich.edu/shame, not the splash page or box on the login screen (see /terminal/index.jinja2) -- I'm guessing that's more useful?

**Comment by arxanas** [comment]
@ppannuto I would check myself but

screen shot 2016-03-17 at 16 09 39

**Comment by ppannuto** [comment]
Ugh.. that's been an outstanding TODO for a while.

I haven't looked at that code for forever. Out of curiousity, what happens
if you just set

ldap.server = ldap.umich.edu
ldap.password = YourPassword
ldap.username = wkhan

or possibly

ldap.username = cn=wkhan

You won't be able to create new users, but the rest may just work?

**Comment by ppannuto** [comment]
I think all of the relevant folks are graduated and gone.

**Pull request closed without merging**
